name: (A) PHPCS
on:
  push:
    branches:
      - '*'
permissions:
  actions: read
  contents: write
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Repo Name
        run: echo "BRANCH=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV
      - name: Trigger Tests
        run: |
          echo "Testing $REPO on branch $BRANCH"
          gh workflow run codetesting.yml -f modules="['$REPO']" -f phpstan_level=0 -f branch=$BRANCH -R UCBoulder/oit_dingo
        env:
          GH_TOKEN: ${{ secrets.RALPHIE_TOKEN }}
          REPO: ${{ github.event.repository.name }}
